{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Let's start by making sure that we can get the lat and lng info out of the googlemaps return object (a dictionary wrapped in a list).  The example is initially taken from "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "37.42380968029149 -122.0829212197085\n"
     ]
    }
   ],
   "source": [
    "import googlemaps\n",
    "from datetime import datetime\n",
    "\n",
    "gmaps = googlemaps.Client(key='AIzaSyCCwdoUJGYzut7CtQTyfghkxW641lhJOY4')\n",
    "\n",
    "# Geocoding an address\n",
    "geocode_result = gmaps.geocode('1600 Amphitheatre Parkway, Mountain View, CA')\n",
    "#print(geocode_result)\n",
    "lat = geocode_result[0]['geometry']['viewport']['northeast']['lat']\n",
    "lng = geocode_result[0]['geometry']['viewport']['northeast']['lng']\n",
    "print (lat,lng)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Now we want to see about plotting this on a map.  I found a library for doing this at https://pypi.python.org/pypi/gmplot/1.0.5.  It will require installation with pip.  It was broken with Python 3.4+.  I found this article that mentioned how to fix it: https://www.reddit.com/r/Python/comments/4bemmb/is_there_a_gmplot_for_python_34/ .  When you run the code before the fix it will produce an error message like:\n",
    "\n",
    "    Traceback (most recent call last):\n",
    "      File \"mapstest.py\", line 1, in <module>\n",
    "        import gmplot\n",
    "      File \"/Users/simpson/anaconda/lib/python3.5/site-packages/gmplot/__init__.py\", line 1, in <module>\n",
    "        from gmplot import GoogleMapPlotter\n",
    "    ImportError: cannot import name 'GoogleMapPlotter'\n",
    "    \n",
    "The long path tells you what directory to look for the files that need changing.  You can use the command line to go there and `nano` to fix the files as requested in the fix.\n",
    "\n",
    "Note that it produces a file in the same directory as this notebook.  You may need to zoom out to see where it drops the pin.  I'm not sure how to play around with this tool all that much since there doesn't seem to be much documentation for it.\n",
    "\n",
    "Note as well that it needs the lat and lng output from the top cell so make sure to run that first."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "import gmplot\n",
    "\n",
    "gmap = gmplot.GoogleMapPlotter(37.428, -122.145, 16)\n",
    "\n",
    "#gmap.plot([lat], [lng], 'cornflowerblue', edge_width=10)\n",
    "#gmap.scatter(more_lats, more_lngs, '#3B0B39', size=40, marker=False)\n",
    "gmap.scatter([lat], [lng], 'k', marker=True)\n",
    "#gmap.heatmap([lat], [lng])\n",
    "\n",
    "gmap.draw(\"mymap.html\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "collapsed": true
   },
   "source": [
    "There is at least one other library to look at but it is pretty complicated and not likely what you are looking for at the moment.  It can create some pretty serious maps though: http://matplotlib.org/basemap/users/examples.html.  There is a lighter intro at http://chrisalbon.com/python/matplotlib_plot_points_on_map.html."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
